data:
    path: D:\code\go\gobot\build\data\
kvdb:
    path: D:\code\go\gobot\build\data\
log:
    level: Info
    path: D:\code\go\gobot\build\log\
login:
    autologin: false
    pwd: HMiYHaup4x422Fa4pCVW2n8MqDm7klVl/e1/4hn3tnA=
    rememberme: true
    username: admin
python:
    path: D:\Program Files (x86)\Python3.8\python.exe
