data:
    path: D:\code\go\gobot\build\data\
kvdb:
    path: D:\code\go\gobot\build\data\
log:
    level: Info
    path: D:\code\go\gobot\build\log\
login:
    autologin: false
    pwd: vDy5gfvvcTl4iw+tV3IeHnH3ZiDSbanE2pNtstlB3yA=
    rememberme: true
    username: admin
python:
    path: D:\Program Files (x86)\Python3.8\python.exe
