data:
    path: D:\code\go\gobot\build\data\
kvdb:
    path: D:\code\go\gobot\build\data\
log:
    level: Info
    path: D:\code\go\gobot\build\log\
login:
    autologin: false
    pwd: /WsEF91X18Tz81E0BU6n6u6PBKI7Dn4BE2/nr1dfPF8=
    rememberme: true
    username: admin
python:
    path: D:\Program Files (x86)\Python3.8\python.exe
