data:
    path: D:\code\go\gobot\build\data\
kvdb:
    path: D:\code\go\gobot\build\data\
log:
    level: Info
    path: D:\code\go\gobot\build\log\
login:
    autologin: false
    pwd: bHl+TnwdTFZYWAyixRiYGO39e3T2l7KWbNZdGywQB7U=
    rememberme: true
    username: admin
python:
    path: D:\Program Files (x86)\Python3.8\python.exe
