kvdb:
  path: "D:\\code\\go\\gobot\\build\\data\\"
log:
  path: "D:\\code\\go\\gobot\\build\\log\\"
  level: "Info"
data:
  path: "D:\\code\\go\\gobot\\build\\data\\"
python:
  path: "D:\\Program Files (x86)\\Python3.8\\python.exe"
