name: deploy

on:
  push:
    tags:
      - 'v*'
env:
  VERRSION: "1.0.12"
jobs:
  deploy-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装 Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.10

      - name: 安装依赖 && 编译
        run: |
          ROOT=$(pwd)
          mkdir -p ${ROOT}/build/bin
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          go mod tidy
          
          cd $ROOT
          brew install upx
          wails build -upx -ldflags "-s -w"

      - name: 上传Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gobot-darwin-amd64-${{ env.VERRSION }}
          path: build/bin

  deploy-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装 Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.10

      - name: 安装依赖 && 编译
        run: |
          $ROOT=$(pwd)
          mkdir -p ${ROOT}\build\bin
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          go mod tidy
          
          cd $ROOT
          choco install -y upx
          wails build -upx

      - name: 上传Artifacts(zip)
        uses: actions/upload-artifact@v3
        with:
          name: gobot-windows-amd64-${{ env.VERRSION }}
          path: |
            build/bin

      - name: 上传Artifacts(installer)
        uses: actions/upload-artifact@v3
        with:
          name: gobot-setup-windows-amd64-${{ env.VERRSION }}
          path: |
            build/*.exe

  deploy-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装 Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.10
      - name: 输出Python信息
        run: ls; echo PYTHON_HOME

      - name: 安装依赖 && 编译
        run: |
          ROOT=$(pwd)
          mkdir -p ${ROOT}/build/bin
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          go mod tidy
          
          cd $ROOT
          sudo apt-get update
          sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev build-essential upx
          wails build -upx -ldflags "-s -w"

      - name: 上传Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gobot-linux-amd64-${{ env.VERRSION }}
          path: build/bin
